### ISSUE TITLE
[UXContent/Strategy] Huge Checkboxes

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/Backlog#1005]
**AC:**
- Strategy, Usage, Restrictions, Accessibility for Huge Checkbox Inputs
- Deliver final Content to Spark Engineering by 5/22

![image](https://user-images.githubusercontent.com/46761151/82109375-6ac1c000-9703-11ea-8976-42ca7ee6504a.png)

**Comment by OlyaKenney** [comment]
Complete and can be closed: UX a11y input was provided to the team.
