### ISSUE TITLE
[DevResearch/Discussion] Datepicker shows up behind modal when Datepicker used in modal

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1038]
**Research**
SME: Amber 
Let's chat about this. Originally we didn't try to remedy any issues with form fields inside forms because we don't recommend people put forms inside modals. There are a bunch of people doing this I think and there is one specific bug with the z-index of the datepicker being lower than the modal so when you open a modal the datepicker shows up behind it. Should we fix this? ( I think we might need too)

**Comment by ssabo1** [comment]
added to backlog
