### ISSUE TITLE
[SprkBuild] Toggle Switch - HTML

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/Backlog#1076]
**User Story:**
As Spark we want to add an Input variant of Toggle Switch to the Design System 

**Notes:**
Requestor: Users, Spark UX
SME: Jane, Virginia 

**AC:**
- New Input Variant will be called [SWITCH?] 
- [Switch] will be an Input Variant https://sparkdesignsystem.com/using-spark/components/input

**Comment by yodasw16** [comment]
https://www.erikkroes.nl/blog/accessible-html-toggle-button-switch/
