### ISSUE TITLE
Highlight Board Upgrades

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1079]
**Notes:**
Will come back to this one after design research #847 

Currently, both components are completely designed in the configuration setup. We should reset these to be composition. There has been lots of complaints about the inflexibility of this component. 

# Angular
-- new for all API work, must support router links
- Change the `type` prop to be called `variant`.

# React
-- new for all API work, must support router links
- Remove all the null `defaultProps`.

**Comment by ssabo1** [comment]
Enhancements are coming. Confirmed with UX 2/4/21 to allow for more flexibility.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
