### ISSUE TITLE
[Research] Should dropdown component allow for disabling the text replacement?

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/Backlog#1089]
When a choice is made, the text in the trigger is replaced by the value of the choice. One use case for the component is a menu-like interface where an action is chosen. In that case, it doesnt make sense to update the trigger text. Our docs dont eliminate this use case explicitly, so would it be appropriate to enable the ability to turn off the replacement?

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
