### ISSUE TITLE
[Enhance] Add Alt Text to new Icon Set

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/Backlog#1102]
**User Story:**
As Spark we want to add Alt Text to our new Icons so that icons are accessible.

**Notes:**
Requestor: Design System SME: Virginia/Olya

**AC:**
- See PO for Alt Text Naming
- Alt Text will be added to New Spark Icons

**Comment by afebbraro** [comment]
SVGs use `<title>` instead of `alt`. We should verify that all of the icons we have all have title text.

**Comment by ssabo1** [comment]
Added to UX backlog
