### ISSUE TITLE
Modal Upgrades

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1138]
Include the following:
https://github.com/sparkdesignsystem/Backlog/issues/1336

# React
-- new for all API work, must support router links
- Change `title` prop because it causes a11y issues.
- `CloseButton.js` and its test file need the `Sprk` prefix.
- `Mask.js` and its test file need the `Sprk` prefix.
- `ModalFooter.js` and its test file need the `Sprk` prefix.
- see todo on line 338 and give the closeIcon prop a default
- Clean up the line lengths
- in `ModalMask.js` change the `clicked` prop to follow our standard, `isClicked` or `isClosed`, since clicking the Mask will close it.
- Fix the eslint errors (lots of them throughout all the components)
- In the ModalFooter, take a look at this and fix it up. We should implement a better solution than ` <p>&nbsp;</p>`.
![Screen Shot 2020-07-23 at 2 16 33 PM](https://user-images.githubusercontent.com/2117593/88334621-47ad2100-ccef-11ea-87da-e8cdda748d9e.png)

# Angular
-- new for all API work, must support router links
- Change `title` prop because it causes a11y issues and add a comment above it. Currently, it has no documentation comment so nothing shows up in storybook.
- Change `modalType` to `variant`
- The modal doesn't use the spark button for the confirm/cancel. Update to use spark button for those. The close button doesn't have any button styles so it can stay as is.
- Clean up the line lengths
- Give ability to change the icon name for the close icon.
- We are bringing in all of lodash when we don't need it all. Update the import statement.

**Comment by ssabo1** [comment]
Enhancements are coming. Confirmed with UX 2/4/21 button placement needs to move to the bottom right.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
