### ISSUE TITLE
Masthead

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1146]
Include when breaking down:
https://github.com/sparkdesignsystem/Backlog/issues/1398
https://github.com/sparkdesignsystem/Backlog/issues/433
https://github.com/sparkdesignsystem/Backlog/issues/407
https://github.com/sparkdesignsystem/Backlog/issues/1408

**Notes:**
- Ask UX about any major changes coming (Confirmed on 2/4/21 there are no Major Changes from UX.)
-- new for all API work, must support router links
Old Issue that was closed: https://github.com/sparkdesignsystem/Backlog/issues/475

**Comment by ssabo1** [comment]
Need to consider the Masthead work that was made on Angular V11.0.1 on 1/27/21.

**Comment by ssabo1** [comment]
Good to break down now. Confirmed on 2/4/21 there are no Major Changes from UX.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
