### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1147]
**Notes:**
Pending UX Review of Pagination
Confirmed on 2/4/21 there are no Major Changes from UX. 

**Not finished. Need to gather developer feedback. Currently, it is configuration based.** 

# React
-- new for all API work, must support router links
- Fix eslint errors
- Remove the need to have users set `variant="default"`. Default should be used if no variant is set.

# Angular
-- new for all API work, must support router links
- Change `paginationType` to be `variant` and remove the default setting of `default` as it does nothing.

**Comment by ssabo1** [comment]
Good to break down now. Confirmed on 2/4/21 there are no Major Changes from UX.

**Comment by bobwise** [comment]
Some more stuff found during an audit:

## HTML
- Bug: disabled links can still be focused and activated with keyboard and screen reader
- chevrons have bad default aria-labels. Recommend matching React - “Previous Page” and “Next Page”.

## Angular
- Bug: disabled links can still be focused and activated with keyboard and screen reader
- chevrons are wrapped in a hard-coded aria-label so the custom label doesn’t do anything
- nav has hardcoded “Pagination Navigation” label that cannot be changed
- chevrons have bad default aria-label. Recommend matching React - “Previous Page” and “Next Page”.

## React
- Bug: disabled links can still be focused and activated with keyboard and screen reader
- chevrons are wrapped in a hard-coded aria-label so the custom label doesn’t do anything
- nav has hardcoded “Pagination Navigation” label that cannot be changed

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
