### ISSUE TITLE
List

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1148]
**Notes:**
Pending UX Research into Spark List #848 
- Notes: The React component uses one SprkList component that takes an element prop to determine if it is unordered or ordered and uses SprkListItems inside. The Angular implementation uses three components, sprk-unordered-list, sprk-ordered-list and sprk-list-item. 

The Angular implementation should be streamlined to be this:

New Unordered
```
<ul sprkList variant="bare" idString="example-1">
  <li sprkListItem analyticsString="my-str">Almonds</li>
  <li sprkListItem idString="example-2">Pizza</li>
  <li sprkListItem>Spinach</li>
</ul>
```

Old Unordered  Implementation
```
    <sprk-unordered-list
      listType="bare"
      idString="unordered-list-2"
    >
      <sprk-list-item idString="list-item-10">
        Bare List Item
      </sprk-list-item>
      <sprk-list-item idString="list-item-11">
        Bare List Item
      </sprk-list-item>
      <sprk-list-item idString="list-item-12">
        Bare List Item
      </sprk-list-item>
    </sprk-unordered-list>
```
New Ordered
```
<ol sprkList variant="indented" idString="example-1">
  <li sprkListItem analyticsString="my-str">List Item 1</li>
  <li sprkListItem idString="example-2">List Item 2</li>
  <li sprkListItem>List Item 3</li>
</ol>
```

Old Unordered
```
    <sprk-ordered-list idString="ordered-list-1">
      <sprk-list-item idString="list-item-4">
        Ordered List Item
      </sprk-list-item>
      <sprk-list-item idString="list-item-5">
        Ordered List Item
      </sprk-list-item>
      <sprk-list-item idString="list-item-6">
        Ordered List Item
      </sprk-list-item>
    </sprk-ordered-list>
```

The advantages of going from three separate components (that only need to add Spark CSS classes) to two new directives.
1. Reduce the number of Spark components that we need to maintain and ship and test.
2. Reduce the need for users to know that there are separate sprk-ordered-list and sprk-unordered-list components. There will be only one now, sprkList.
3. Allow users to add any attributes they want to their lists. With the current setup, they cannot add any sort of Aria attributes for example.

The disadvantages to creating the new directives and phasing out the old components
1. The current implement works and we don't usually have changes to lists.
2. We haven't received any negative feedback on current implementation.
3. Developers would now need to copy or remember that an unordered list is a `<ul>` and that an ordered list is `<ol>`.

# Angular
-- new for all API work, must support router links
- In the sprk-unordered-list and ordered components change the `listType` prop to be `variant` and add typings for `bare` or `indented`
- Follow the streamline implementation above. Deprecate the `sprk-unordered-list` and `sprk-ordered-list`, `sprk-list-item` component. Add `sprkList` and `sprkListItem`.
- Update any components that use the old list to use the new ones.
- Make new issues to remove the old code for `sprk-unordered-list` and `sprk-ordered-list`, `sprk-list-item` in the following release cycle.
- Update the stories

# React
-- new for all API work, must support router links
- Remove empty default props
- Remove empty default props from `SprkListItem.js`
- Fix eslint errors in list and list item

**Comment by afebbraro** [comment]
Ready for groooming.

**Comment by ssabo1** [comment]
Still ready for Grooming @afebbraro ?? Confirmed on 2/4/21 there are no Major Changes from UX.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
