### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1154]
Include in the upgrade:
https://github.com/sparkdesignsystem/Backlog/issues/1406

Notes: INCOMPLETE ISSUE
- Holding off till UX research #853 
- The angular component is composition. The react is configuration with an option of 'html'.

# React
-- new for all API work, must support router links
- Fix eslint errors
- Change `additionalContainerClasses` to `containerAdditionalClasses`
- Change `additionalTableClasses` to `tableAdditionalClasses`
- Remove empty default props
- Remove variant option of `default`. It doesn't do anything and is unnecessary. 

# Angular
-- new for all API work, must support router links
- Change `additionalTableClasses` to `tableAdditionalClasses`

**Comment by ssabo1** [comment]
Enhancements are coming. Confirmed with UX 2/4/21

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
