### ISSUE TITLE
Stepper

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1157]
Include in Upgrades:
https://github.com/sparkdesignsystem/Backlog/issues/1407

# React
-- new for all API work, must support router links
- Fix eslint errors in main component and subcomponents and story file. There are some pretty serious ones like "do not use ReactDOM.findDOMNode". Docs say "Facebook will eventually deprecate findDOMNode as it blocks certain improvements in React in the future. It is recommended to use callback refs instead"
- StepperStep, add children to proptypes
- Remove empty default props
- Change `title` prop on step to `heading` in slider and step. This is something we are doing across the DS to avoid a11y issues.

# Angular
-- new for all API work, must support router links
- Stepper is not built in Angular - there is a file there but the component is not complete.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
