### ISSUE TITLE
[Remove] deprecation Spark CSS: Remove utility width class need on TextInput

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1177]
This needs to be pushed out with a major release. 

**User Story:**
As Spark, we want inputs to have width of 100% set on the so that we are no longer using a !important utility.
Deprecation Strategy: http://shorty/designsystemplaybook

**Notes:**
SME: Amber
Right now for our inputs we apply the utility of `sprk-u-Width-100` to all of them. We should update inputs to have width:100% set on them instead of using a !important utility.

**AC:**
- inputs will have width:100% set on them

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
