### ISSUE TITLE
[Remove] deprecation work: angular Angular Inputs

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1182]
**User Story:**
As Spark, once we release Input Component API upgrade, then we want to remove the code the following Major Release.

**Notes:**
SME: Amber

**AC:**
- the following will be removed from `sprk-input-container`
```
      <ng-content select="[sprk-select-icon]"></ng-content>
      <ng-content select="sprk-selection-item-container"></ng-content>
```
- `sprk-icon-input-container` and 'sprk-huge-input-container' components will be removed.

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
