### ISSUE TITLE
[Enhance] Tooltip Z-index default value is incorrect

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#1189]
**User Story:**
As Spark, we want Tooltip to render correctly when it overlaps with any component with a z-index so that tooltip always renders above all other elements.

**Note:**
Requestor: SME: Bob
To reproduce this, the tooltip icon must be in the lower half of the viewport so that the tooltip renders above the icon.

**Current State:**
With default settings, the spark tooltip is rendering below the Masthead. The tooltip should always render above all other elements.

![image](https://user-images.githubusercontent.com/1424560/91739227-9c11af00-eb7f-11ea-8fd4-75d16d298048.png)

**AC:**
- Tooltip will render correctly when it overlaps with Masthead - All Frameworks
- Tooltip will render correctly when it overlaps with Modal  - All Frameworks
- Tooltip will render correctly when it overlaps with any component with a z-index  - All Frameworks

**Comment by ssabo1** [comment]
added to backlog
