### ISSUE TITLE
[REMOVE] deprecated spinner functionality from Button [Angular] - Part 1

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/Backlog#1313]
**User Story:**
As Spark we want Remove deprecated spinner so that we have replaced with sprk-spinner directive

**Notes:**
SME: RV
Deprecation Strategy: http://shorty/designsystemplaybook
BREAKING CHANGE: Remove deprecated spinner and to be fully replaced with sprk-spinner directive
PR https://github.com/sparkdesignsystem/spark-design-system/pull/3555
Issue: https://github.com/sparkdesignsystem/spark-design-system/issues/3316

**AC:**
Tasks: Go through PR and to all `TODO`s to fully remove deprecated spinner
- Ensure documentation is updated
- Update release notes and add to upgrade guide

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
