### ISSUE TITLE
[Remove] deprecated spinner functionality from Button [React] - Part 2

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/Backlog#1314]
**User Story:**
As Spark we want to Remove deprecated spinner so that it will be replaced with the compositional spinner.

**Notes:**
SME: RV
Deprecation Strategy: http://shorty/designsystemplaybook
BREAKING CHANGE: Remove deprecated spinner and to be fully replaced with the compositional spinner
PR: https://github.com/sparkdesignsystem/spark-design-system/pull/3552
Issue: sparkdesignsystem/spark-design-system#3317

**AC:**
Tasks: Go through PR and to all `TODO`s to fully remove deprecated spinner
- Ensure documentation is updated
- Update release notes and add to upgrade guide

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
