### ISSUE TITLE
[Remove] Deprecated React Tab functionality

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#1315]
**User Story:**
As Spark we want to Remove deprecated props from SprkTabs, SprkTabsButton, and SprkTabsPanel so that they are no longer in the code.

**Notes:**
SME: Bob
Deprecation Strategy: http://shorty/designsystemplaybook
BREAKING CHANGE: Remove deprecated props from SprkTabs, SprkTabsButton, and SprkTabsPanel.
PR: https://github.com/sparkdesignsystem/spark-design-system/pull/3565
Issue: sparkdesignsystem/spark-design-system#3297

**AC:**
Tasks: Go through PR and to all `TODO`s to fully remove deprecated functionality
- Ensure documentation is updated
- Update release notes and add to upgrade guide

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
