### ISSUE TITLE
[Remove] deprecated spinner functionality from Button - HTML Part 3

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/Backlog#1316]
**User Story:**
As Spark we want to Remove deprecated aria roles from HTML Button so that it's no longer in the code.

**Notes:**
SME: RV
Deprecation Strategy: http://shorty/designsystemplaybook
Breaking!
PR: 📌Update when created
Issue: https://github.com/sparkdesignsystem/spark-design-system/issues/3594

**AC:**
- Tasks: Go through PR and to all TODOs to fully remove deprecated spinner
- Ensure documentation is updated
- Update release notes and add to upgrade guide

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
