### ISSUE TITLE
[Add] forwardedRef prop to the SprkSelectionInput -  React.

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/Backlog#1361]
**User Story:**
As Spark we want to add a `forwardedRef` prop to the `SprkSelectionInput` React so that users can show an error if an option from the select is not selected on submit, or on blur if a value is not selected. 

**Notes:**
Requestor: Rocket Loans, Adrean OHalloran 12/14

**AC:**
- will see `forwardedRef` prop to the `SprkSelectionInput` React.

**Comment by AdreanOHalloran** [comment]
Hi I originally raised this issue. Have some proposed changes in PR. Let me know if I can be of further assistance. https://github.com/sparkdesignsystem/spark-design-system/pull/3728

**Comment by ssabo1** [comment]
This will be with the API work.
