### ISSUE TITLE
[bug] formatter prop doesn't work in the React SprkRevealInput

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#1365]
## Describe The Bug
The prop is not hooked up and doesn't do what the description says it does. You can pass in the function but it doesnt get executed because it is not hooked up. THis is working and hooked up in the SprkTextInput.js. See that file for more information.

What our docs say it does:
```
  /**
   * A function supplied will be passed
   * the value of the input and then executed,
   * if the valid prop is true. The value
   * returned will be assigned to the value of the input.
   */
  formatter: PropTypes.func,
```

## Expected Behavior
The prop should do what the description says.

**Comment by bobwise** [comment]
I believe this is working as intended. This can be tested on our [demo site](https://spark-testreact.netlify.app/input/reveal-input).

The demo site example is set up with the Spark SSN Formatter:
```
<SprkRevealInput
  errorMessage="There is an error in this field."
  formatter={sprkFormatSSN}
  valid={sprkIsValidSSN(ssn)}
  value={ssn}
  onChange={this.handleChange}
  label="Social Security Number"
  toggleLabel="Show SSN"
  name="ssn"
/>
```

When I add text to the input, the `sprkIsValidSSN` function marks the field as invalid on every keystroke...
![image](https://user-images.githubusercontent.com/1424560/103913747-e4654e80-50d6-11eb-8126-e12ee4ef01b5.png)

.. until the validator returns `true`, in which case it applies `sprkFormatSSN` and sets the input value to the returned value.

![image](https://user-images.githubusercontent.com/1424560/103913764-ec24f300-50d6-11eb-9fe9-ada474944bdf.png)

It also works with custom `formatter` functions:

```
<SprkRevealInput
  formatter={(value) => {
      let val = value.trim().replace(/-/g, '');
      let newVal = '';
      const sizes = [3, 3, 3];
  
      sizes.forEach((size) => {
        if (val.length > size) {
          newVal += `${val.substr(0, size)}$`;
          val = val.substr(size);
        }
      });
  
      newVal += val;
      return newVal;
    }
  }
[...]
```

![image](https://user-images.githubusercontent.com/1424560/103914220-7e2cfb80-50d7-11eb-855f-577462ac37f7.png)
![image](https://user-images.githubusercontent.com/1424560/103914236-838a4600-50d7-11eb-915e-6b2531bde352.png)

**Comment by ssabo1** [comment]
This will be covered with Inputs API work.
