### ISSUE TITLE
Make SparkDesignSystem.com responsive at 320 px [I]

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#1372]
**User Story:**
As Spark we want Design System Site to render without horizontal scrollbars at 320px since it is required for level AA compliance.

**Notes:**
- Cards on the homepage. - will be done with the IA update https://github.com/sparkdesignsystem/Backlog/issues/1392 
- [Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)
- ignore Tables, Homepage Cards , Masthead example

**AC:**
* Remove embedded YouTube Frames.
* Spark Design system will be responsive at 320.

**Comment by ssabo1** [comment]
Plan to work with Tables after UX research and maybe include with API Upgrade.
