### ISSUE TITLE
[Request] Fully Selectable Spark Card

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/Backlog#1394]
**Requestor:** Brand Marketing
**SME:** Janina

**Request:**
Spark Card: https://sparkdesignsystem.com/using-spark/components/card/

**Issue:**
RM needs the whole card to be clickable.

![image.png](https://images.zenhubusercontent.com/5c98da1df75c1c000158e457/dbc8788d-509a-47a3-ad3d-5771be4421f7)

**Comment by afebbraro** [comment]
Could wrap the card in a link. Is that what you mean?

**Comment by ssabo1** [comment]
Include with Card API upgrades https://github.com/sparkdesignsystem/Backlog/issues/1036

**Comment by ssabo1** [comment]
UX sees no concerns with this enhancement to Spark Cards.

**Comment by afebbraro** [comment]
I verified it works in new version. They would wrap the component inner markup in link.
