### ISSUE TITLE
Angular Pagination - long-term solution for click event bug - BREAKING

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#189]
**AC:**
- Add Permanent fix for Spark.
- document in release notes

## Describe The Bug
A previous version of the Angular Pagination component introduced this bug:

![image](https://user-images.githubusercontent.com/1424560/63539544-5809ba00-c4e8-11e9-8508-2dea0bc78889.png)

`goToPage` emits the page number of the newly-selected page while `goBack` and `goForward` emit the page number of the previously-selected page. Users expect these events to emit the newly-selected page.

As a temporary solution, we made this change in Issue https://github.com/sparkdesignsystem/spark-design-system/issues/1401. A goal with this change was to not create a breaking change.

![image](https://user-images.githubusercontent.com/1424560/63539637-8daea300-c4e8-11e9-8e1c-08c92afe5b36.png)

This Issue is to remove the temporary non-breaking solution and put in place a permanent breaking solution.

## To Reproduce
1. Go to the pagination test page in the Angular dev site
2. Set these click events to log their output object
3. Click one of the clickable elements in the pagination control
4. Observe the log result

## Expected Behavior
`goBack`, `goForward`, and `goToPage` should all emit the new page number in the `page` property. These may also need to be combined into a single event like the React component does.

**Comment by ssabo1** [comment]
This is no longer needed at 1401.

**Comment by ssabo1** [comment]
added to backlog
