### ISSUE TITLE
Stepper A11y Update

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/Backlog#261]
SADR Breakdown.

**User Story:**
As Spark we want our Stepper to be accessible. HTML & React

**Notes:**
Requested from RM Accessibility Audit back in November 2019. 
- Audit Missing visual indication of focus RM-4 
- "Here's how it works" tab panel is not accessible RM-24

Included above
- potential: ignore carousel by screen readers

### PO CLEAN UP AC BELOW

**AC:**
- Stepper will read tab content in addition to tab count
- Screen reader will be able to use its screen reader functionality to read stepper content
- Stepper tab list will have Title / Useful Text
- Enhance Aria Controls, Aria controls will be on the Tab (not span)
- ID on the Span inside of the tab needs to move to the tab its self. 
- Tabbed panel will be moved outside of the tab. (this will cause a style issue)
- Tabbed Panel will have a Tab Index

**Issue:**
As Spark, we either update `aria-orientation` programatically as the page reflows or get rid of it.
 `aria-orientation` https://www.maxability.co.in/2019/05/top-7-aria-tips-for-developers/
- Why did we add it? 
- What does it do that we want? 
- How will it alter the display of the component? 
- how does this component sound to screen readers? 
- How does interacting with the Carousel work?

**Issue:**
Requestor: Alan 1/24/20
Small Screen - Accessibility: Cant use keyboard arrows on small screen 

Steps to Reproduce:
1. Shrink your screen
2. go to https://sparkdesignsystem.com/patterns/components/stepper, STEPPER WITH CAROUSEL
3. Try using arrow keys 

**AC:**
- How should this function on small screen? - UX

**Comment by ssabo1** [comment]
## Describe The Bug
The animation for the Stepper component is sometimes incorrect when viewed in Firefox. This appears to be a race condition. This has been observed in Vanilla and in React.

## To Reproduce
Steps to reproduce the behavior:
1. Render a Stepper in Firefox
2. Change the step a bunch and watch for the animation failure. The text should turn transparent before the slider begins to move, but this is not always the case.

## Expected Behavior
The text in the slider should turn transparent, then the slider should move, then the text should fade back to opaque.

## Screenshots
![stepper](https://user-images.githubusercontent.com/1424560/61974293-2f0f0b80-afb4-11e9-873d-8a1026fa083a.gif)

## Environment
 - This bug has only been observed in Firefox (desktop, version 66.0.2 on OS X)

**Comment by guern1kn** [comment]
Virginia found this example of using roving tabindex that may be helpful when tackling this task.
https://www.youtube.com/watch?v=uCIC2L
