### ISSUE TITLE
[BUG] Masthead Big Nav dropdowns in Angular

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#394]
This is vanilla:
![image](https://user-images.githubusercontent.com/46761151/80326908-4a8b9900-8808-11ea-9e91-0075385752dd.png)

This is angular: 
![image](https://user-images.githubusercontent.com/46761151/80326919-57a88800-8808-11ea-9c14-7856edcea908.png)

**Comment by ssabo1** [comment]
added to backlog
