### ISSUE TITLE
[UXDesign] Redesign SASS Docs Page

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/Backlog#402]
**User Story:**
As Spark we want to redesign our SASS docs page so that it's easier to navigate for our users.

Redesign SASS Doc Page:
https://sparkdesignsystem.com/using-spark/foundations/sass-variables

Design similar to CSS utils? or Enhance that one as well?
css utils: https://sparkdesignsystem.com/using-spark/foundations/sass-variables

**Comment by ssabo1** [comment]
Repurposed this issue after grooming with Amber and Rob to start with Design.

**Comment by ssabo1** [comment]
This Page has been redesigned to Design Tokens.
