### ISSUE TITLE
[DevResearch/Discussion] Internal Components like `SprkStepperStep`

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/Backlog#404]
## Proposal Title
React
Certain components weren't really meant to be available for public consumption.
For example, `SprkStepperStep` has prop configurations that should not be changed by external consumers. (`onClick`, `hasDarkBackground`, `hasDescription`)

But these components showing in Storybook.

So we need to discuss:
- Is storybook for developing spark components?
- Is storybook for consumers of spark?
- Both? What do we do to balance what we show 

Other Components:
- SprkTabsButtons.js

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [x] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [x] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by ssabo1** [comment]
Closing at this time. Users need to be able to see the props on the internal components.
