### ISSUE TITLE
[Build] SSN Input validation improvements - Vanilla

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/Backlog#414]
**User Story:**
As a Spark Vanilla user I want to see SSN input validations in Spark so that user can only enter a valid SSN.

Notes:
- This is for Spark Vanilla
- current validation exist in js file.

**AC:**
1. Should not show error when user begins typing.
2. Should show error if user is finished typing and input is invalid (input / blur).
3. Should not allow any input but numbers or dashes.

**Comment by ssabo1** [comment]
Will be Covered in #598
