### ISSUE TITLE
SprkTable + SprkMastheadBigNav uses `additionalContainerClasses` instead of `additionalClasses` - React.  

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/Backlog#429]
## Proposal Title
Anytime we use `additionalClasses` prop, we're implying it's the outermost div.
In React SprkTable amd SprkMastheadBigNav, we're using `additionalContainerClasses` which is inconsistent.

**Notes:**
- Breaking.

**AC:**
- additionalTableClasses goes into tableAdditionalClasses
- SprkTable `additionalContainerClasses`  will be changed to `additionalClasses`
- SprkMastheadBigNav `links.additionalContainerClasses` will be changed to `links.additionalClasses` 

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [ ] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by ssabo1** [comment]
Confirmed: This has been added to Spark Design System Team Backlog.
