### ISSUE TITLE
SprkModal.js `closeIcon` Prop does not have a default even though it implies it does - React

### ISSUE THREAD

**Issue by RVMendoza** [sparkdesignsystem/Backlog#431]
## Proposal Title
React
SprkModal.js's prop documentation implies that `closeIcon` will default to "close" and it's not reflecting that in the default props.

Even if this fall back function happens within the code, we should be doing this within the prop defaults, and not the code anyways.

**AC:**
- Add a default to `closeIcon` in SprkModal.js

![image](https://user-images.githubusercontent.com/4342363/71995884-4744b100-3209-11ea-8396-b53706331a2e.png)

## Type of change
Please select only 1.
* [ ] New Component
* [x] Enhancement to existing component
* [ ] Substantial documentation change
* [ ] Changes to the design or features of [sparkdesignsystem.com](http://sparkdesignsystem.com)

## Change category
Select as many as apply.
* [ ] **Visual** (Changes to the visual design of a component)
* [ ] **UX** (Change the user experience design of a component)
* [x] **Component** (Modifying the functionality of a component)
* [x] **Editorial** (Changes to documentation or content style)
* [ ] **Code Style** (Changes to the way code is written or the component architecture)
* [ ] **Accessibility** (Substantial changes to a component's accessibility)

**Comment by ssabo1** [comment]
added to backlog
