### ISSUE TITLE
[Enhancement] Remove Spark dependency & fix toggle animation

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#479]
**User Story:**
As Spark we want to remove the spark dependency on `dom-slider` and write it ourselves. This pkg animates height. Once the new slider is written, this will fix the RMO Toggle animation jump.

**Notes:**
Requestor: Amber with a side request from RMO, "Clicking the toggle on items expands the content, but bounces - not smooth like current day"

**AC:**
- Write new JS for Toggle/Accordion/Masthead
- functions must be exportable
- Remove the spark dependency on `dom-slider` package
- toggle animation jump
- When clicking toggle, item will expand the content (toggle animation will not jump)

**Comment by ssabo1** [comment]
Binx OUT.
