### ISSUE TITLE
Audit React components for `children.map`

### ISSUE THREAD

**Issue by 13protons** [sparkdesignsystem/Backlog#480]
**User Story:**
As Spark we want to make sure we're not using children.map, so that we use the preferred React.children.map instead. 

**Notes:**
- Functions are valid values for props.children, but if you call children.map on a function it will blow up.
- See [here](https://mxstbr.blog/2017/02/react-children-deepdive/#looping-over-children) for more info

**AC:**
- Audit React Components 
- React Components will no longer use children.map
- React Components using children.map will be replaced with React.children.map

**Comment by ssabo1** [comment]
migrated to updated backlog

**Comment by ssabo1** [comment]
Closing at this time.
