### ISSUE TITLE
React Stepper will provide error messaging for fewer than 2 steps

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#485]
**User Story:**
As Spark, we want our React Stepper will provide error message for fewer than 2 steps 

**Notes:**
- Spark React Stepper had been merged for the July 1st Release, but there is some outstanding work needed to complete the component. 
- There is an additional Issue for adding the Carousel functionality. sparkdesignsystem/spark-design-system#1544 
- Docs say 2 steps or less

**AC:**
-  consistent messaging on stepper docs page
- Stepper React will provide error message

**Comment by ssabo1** [comment]
Closing at this time. Will address as issue becomes prioritized.
