### ISSUE TITLE
Change `imgSrc` to `carouselImg` on `SprkStepperStep` - Stepper/Carousel React

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#487]
**User Story:**
As Spark we started implementing the Carousel component already and need to complete the work. 

**Notes:**
- Bob start the initial work for React Carousel  
https://sparkdesignsystem.com/patterns/components/stepper 

**AC:**
- change `imgSrc` to `carouselImg` on `SprkStepperStep`.

**Comment by ssabo1** [comment]
Closing at this time. Will address as issue becomes prioritized.
