### ISSUE TITLE
Stand up a demo Angular-Universal app to make sure everything works server side

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/Backlog#518]
**User Story:**
As Spark I want to stand up a demo Angular-Universal app so that I make sure everything works server side.

**Notes:**

**AC:**
1. find a angular universe demo app 
2. add spark into it
3. make sure spark performs without issues

**Comment by ssabo1** [comment]
migrated to backlog

**Comment by ssabo1** [comment]
clean up, closing at this time.
