### ISSUE TITLE
Should Bind spark's event handlers to body instead of individual elements

### ISSUE THREAD

**Issue by RCopeland** [sparkdesignsystem/Backlog#530]
**Issue:**
Dynamically created elements dont have js in vanilla. For the use case where things are added dynamically after the dom is ready.

**Notes:**
Requestor: Carlos (using work arounds since 2018)
regular Js

**AC:**
- research, is this a larger issue than we think?

**Comment by ssabo1** [comment]
This is no longer an issue. Servicing moved their app to angular.
