### ISSUE TITLE
[Research] Look into CMS options

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#536]
**User Story:**
As Spark we want to research a CMS that allows us to update content across three different frameworks so that we dont have to maintain 3 different content spots with identical content. 

**Notes:**
- Is Ingenix an option or nah?? 

**AC:**
 - Research CMS Options
- Discuss Options with the Team
- Follow up with PO to create and Implement CMS Option

**Comment by ssabo1** [comment]
Added to backlog.
