### ISSUE TITLE
Should Spark add a Typescript typings file for spark-html and/or spark-react?

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#538]
**User Story:**
As a user adding spinners to buttons, I do not want to see a warning.
 
**Note:**
Requestor: Brendon Kirchner 2/20 8:55am

**AC:**
Example issue of adding spinners to buttons. There is a warning thrown saying that a typings file can't be found. For example, If you take a look our docs for buttons, you can see we are importing the Vanilla JS into our button docs component to add the spinner.

**Comment by ssabo1** [comment]
Added to backlog.
