### ISSUE TITLE
How should Spark implement Design Tokens?

### ISSUE THREAD

**Issue by yodasw16** [sparkdesignsystem/Backlog#540]
On Hold during this time till we rethink the architecture** 

Here's some research to look through.

Articles
- https://medium.com/eightshapes-llc/tokens-in-design-systems-25dd82d58421
- https://dbanks.design/blog/documenting-design-tokens/
- https://medium.com/@kylegach/the-themes-are-always-changing-but-the-tokens-stay-the-same-258d57b18f31
- https://uxdesign.cc/design-tokens-for-dummies-8acebf010d71

Systems
- https://www.lightningdesignsystem.com/design-tokens/
- https://github.com/Shopify/polaris-tokens
- https://comet.discoveryeducation.com/visual-language/tokens.html
- https://github.com/rei/rei-cedar-tokens

Tools
- https://github.com/salesforce-ux/theo
- https://github.com/amzn/style-dictionary
- https://github.com/NateBaldwinDesign/dragoman
- https://github.com/mrmartineau/design-system-utils

**Comment by ssabo1** [comment]
Design Tokens were added to Design Systems in 2020. https://github.com/sparkdesignsystem/spark-design-system/releases/tag/november-30-2020
