### ISSUE TITLE
[DevResearch] Discuss Pagination Component Structure

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#547]
This needs to be reviewed from a design stand point, when the numbers go up, the arrow moves. Pending: 

**Issue:**
Very minor semantic change with very low impact, but it is potentially a breaking change that should be discussed with the team. This was shot down in the past. Applies to all frameworks.

**AC:**
Discuss proposed changes to the structure of the Pagination component.
1. Should it be a `<ul>` or a `<ol>`? Answer: Bob & Dave: Pagination numbers should be an `<ol>` not an `<ul>`
2. Should the chevrons be part of the list?
3. Should it be a list at all?

![image](https://user-images.githubusercontent.com/1424560/62956716-6ad20f80-bdc1-11e9-8f3b-1e32851732bf.png)

**Comment by ssabo1** [comment]
Added to backlog.
