### ISSUE TITLE
[Research] Spark select element will return everything as string instead of origin object/value 

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#549]
**User Story:**
This was from a support request we received on July 9, 2019 @ 6:06pm. Reported in spark angular version. Please report outcome of research here as a comment so that those that are tracking this can see the outcome.

> I found a bug that Spark select element will return everything as string instead of origin object/value

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/308696/62058758-eb084a80-b1ef-11e9-9509-7ddde0d9c4d3.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/308696/62058762-ed6aa480-b1ef-11e9-9355-86618caab487.png)

**Notes:**
Check with Amber*** whats the result... 

**AC:**

**Comment by ssabo1** [comment]
Added to backlog.
