### ISSUE TITLE
Angular 9 Upgrade: Remove {static: true} and {static: false} arguments from ViewChild and ContentChild

### ISSUE THREAD

**Issue by afebbraro** [sparkdesignsystem/Backlog#8]
**User Story:**
As Spark we want to Remove {static: true} and {static: false} arguments from ViewChild and ContentChild because it will no longer be needed in Angular 9.

**Notes:** 
Adding this was needed for the upgrade to Angular 8 and will no longer be needed in Angular 9. 

**AC:**
- Remove {static: true} and {static: false} arguments from ViewChild and ContentChild

**Comment by afebbraro** [comment]
this is research I did a while ago on one thing that will need to be done as part of angular 9 upgrade

**Comment by ssabo1** [comment]
If this was removed we wouldn't be compatible in Angular 8. Closing for now unless testing brings this back up.
