### ISSUE TITLE
[UXa11y] New Green a11y color

### ISSUE THREAD

**Issue by ssabo1** [sparkdesignsystem/Backlog#957]

**Comment by OlyaKenney** [comment]
Completed research and testing to identify the new Green a11y color in collaboration with Spark and Brand teams. Currently waiting for feedback from Jane. Contact for additional insights/documents.

**Comment by OlyaKenney** [comment]
This task is DONE. (In my communication with Jane, we confirmed that new green shade is #008473 and established that #007667 is a good Hover color.) I recommend confirming with Jane as next step in case if she had any follow-up communication with the Brand Team.
