### ISSUE TITLE
[Research] Radio Button - A11y - All Packages [I]

### ISSUE THREAD

**Issue by bobwise** [sparkdesignsystem/Backlog#998]
**User Story:**
As Spark should we add `role="radiogroup"` to the `<fieldset>` so that VoiceOver will announce it is a radio group. 

**Notes:**
- This is for Radio, We do NOT want this for checkboxes
- This will be on the sparkselectioncontainer / 2 levels of ng

**AC:**
- Radio Buttons should follow ARIA guidelines here https://www.w3.org/TR/wai-aria-practices/#wai-aria-roles-states-and-properties-15
- Research: What is Spark doing today?

**Comment by ssabo1** [comment]
Pending Audit

**Comment by ssabo1** [comment]
What is our current state? Did we already research the standard??
